image: gradle:8.7-jdk21

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - docker
  - deploy

#include:
#  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKER_DRIVER: overlay2
  KUBE_CONFIG: "${KUBE_CONFIG}" # base64 encoded kubeconfig stored in GitLab CI variables
  KUSTOMIZE_DIR: "kustomize/overlays/prod"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export DOCKER_HOST="tcp://docker:2375" # Needed for Testcontainers in CI

services:
  - name: docker:dind
    alias: docker

include:
  - 'account-service/ci/build-service.yml'
  - 'creditcard-service/ci/build-service.yml'
  - 'product-service/ci/build-service.yml'
  - 'zos-connect-service/ci/build-service.yml'
