server:
  port: 8091
spring:
  application:
    name: ${CONFIGURATION_SERVICE_APPLICATION_NAME}
  profiles:
    active: native
    # active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
        # git:
        #   uri: "https://github.com/agilesolutions/spring-cloud-config.git"
        #   default-label: main
        #   timeout: 5
        #   clone-on-start: true
        #   force-pull: true
  rabbitmq:
    host: ${RABBITMQ_SERVICE_URL}
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus, refresh, bus-refresh, bus-env, monitor
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

info:
  app:
    name: "Configuration Service"
    description: "Centralized configuration service for managing application properties across environments and services."
    version: "1.0.0"