server:
  port: 8084

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus, refresh, bus-refresh, bus-env
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development
  otlp:
    metrics:
      export:
        url: http://${LGTM_SERVICE_URL}:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://${LGTM_SERVICE_URL}:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://${LGTM_SERVICE_URL}:4318/v1/logs

spring:
  application:
    name: ${ZOS_CONNECT_SERVICE_APPLICATION_NAME}
  mvc:
    apiversion:
      use:
        header: "API-Version"
  config:
    import: ${SPRING_CONFIG_IMPORT}
  # Spring Bus for RabbitMQ to refresh configuration across services
  rabbitmq:
    host: ${RABBITMQ_SERVICE_URL}
    port: 5672
    username: "admin"
    password: "admin"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1

springdoc:
  #  enable-spring-security: true
  #  show-login-endpoint: true
  #  show-oauth2-endpoints: true
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha


logging:
  level:
    root: INFO

info:
  app:
    name: "Cobol Legacy Mock Service"
    description: "Mock service to simulate a Cobol legacy service for demo purposes"
    version: "1.0.0"