apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: services
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: agilesolutions/product-service:1.0.1
          ports:
            - containerPort: 8084
          env:
            - name: PRODUCT_SERVICE_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: PRODUCT_SERVICE_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: LGTM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: LGTM_SERVICE_URL
            - name: RABBITMQ_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: RABBITMQ_SERVICE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: REDIS_HOST