server:
  port: 8080

spring:
  application:
    name: ${GATEWAY_APPLICATION_NAME}
  config:
    import: ${SPRING_CONFIG_IMPORT}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVICE_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 2000

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: ALWAYS
    gateway:
      access: UNRESTRICTED

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

logging:
  level:
    com.agilesolutions.gateway: DEBUG

info:
  app:
    name: "Gateway Service"
    description: "API Gateway for routing requests to backend services and handling cross-cutting concerns such as authentication and logging."
    version: "1.0.0"