spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8091/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8092

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: ALWAYS
    gateway:
      access: UNRESTRICTED

logging:
  level:
    com.agilesolutions.gateway: DEBUG

info:
  app:
    name: "Gateway Service"
    description: "API Gateway for routing requests to backend services and handling cross-cutting concerns such as authentication and logging."
    version: "1.0.0"