apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: services
spec:
  type: ClusterIP  # internal-only, exposed via Ingress
  ports:
    - name: http
      port: 8091
      targetPort: 8091