server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # =========================
        # Legacy (z/OS Connect)
        # =========================
        - id: legacy-account-route
          uri: lb://account-service
          predicates:
            - Path=/legacy/api/accounts/**
          filters:
            # The gateway only validates the JWT and forwards it as a Bearer token to downstream services
            # - AddRequestHeader=Authorization,#{request.headers['Authorization']}
            # Recommended: Remove the session cookie so downstream services only see the Bearer token
            - RemoveRequestHeader=Cookie
            # Baseline the API version for legacy services, this can be used by downstream services to route to the correct controller or service implementation
            - AddRequestHeader=API-Version, 1.0+
            # Forwards the original request path as a header, this can be used by downstream services to route to the correct controller or service implementation
            - StripPrefix=1

        - id: legacy-creditcard-service-route
          uri: lb://creditcard-service
          predicates:
            - Path=/legacy/api/cards/**
          filters:
            # Relays the access token to the downstream service, omit the clientRegistrationId to forward the OAuth2 access token of the currently authenticated user
            # Recommended: Remove the session cookie so downstream services only see the Bearer token
            - RemoveRequestHeader=Cookie
            # Baseline the API version for legacy services, this can be used by downstream services to route to the correct controller or service implementation
            - AddRequestHeader=API-Version, 1.0+
            - StripPrefix=1


        - id: legacy-product-service-route
          uri: lb://product-service
          predicates:
            - Path=/legacy/api/assets/**
          filters:
            # Relays the access token to the downstream service, omit the clientRegistrationId to forward the OAuth2 access token of the currently authenticated user
            # Recommended: Remove the session cookie so downstream services only see the Bearer token
            - RemoveRequestHeader=Cookie
            # Baseline the API version for legacy services, this can be used by downstream services to route to the correct controller or service implementation
            - AddRequestHeader=API-Version, 1.0+
            - StripPrefix=1


        # =========================
        # New Microservices
        # =========================
        - id: account-service-route
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**, /api/depositAccounts/**
          filters:
            # Relays the access token to the downstream service, omit the clientRegistrationId to forward the OAuth2 access token of the currently authenticated user
            # Recommended: Remove the session cookie so downstream services only see the Bearer token
            - RemoveRequestHeader=Cookie
            # Baseline the API version for new microservices, this can be used by downstream services to route to the correct controller or service implementation
            - AddRequestHeader=API-Version, 2.0+

        - id: creditcard-service-route
          uri: lb://creditcard-service
          predicates:
            - Path=/api/cards/**, /api/credit-cards/**
          filters:
            # Relays the access token to the downstream service, omit the clientRegistrationId to forward the OAuth2 access token of the currently authenticated user
            # Recommended: Remove the session cookie so downstream services only see the Bearer token
            - RemoveRequestHeader=Cookie
            # Baseline the API version for new microservices, this can be used by downstream services to route to the correct controller or service implementation
            - AddRequestHeader=API-Version, 2.0+

        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/assets/**
          filters:
            # Relays the access token to the downstream service, omit the clientRegistrationId to forward the OAuth2 access token of the currently authenticated user
            # Recommended: Remove the session cookie so downstream services only see the Bearer token
            - RemoveRequestHeader=Cookie
            # Baseline the API version for new microservices, this can be used by downstream services to route to the correct controller or service implementation
            - AddRequestHeader=API-Version, 2.0+

        # =========================
        # propagate the authorization service name by using the Spring Cloud Gateway as a middleman
        # =========================
        - id: auth-service-route
          uri: lb://authorization-service
          predicates:
            - Path=/.well-known/openid-configuration, /protocol/openid-connect/**

        # =========================
        # Strangler Fig - Dual Run
        # =========================
        - id: strangler-account-route
          uri: lb://account-service
          predicates:
            - Path=/strangler/accounts/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: X-Legacy-Url
                value: http://mock-zosconnect/zos/accounts