apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: services
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: agilesolutions/gateway:1.0.1
          ports:
            - containerPort: 8082
          env:
            - name: GATEWAY_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: GATEWAY_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: REDIS_HOST
            - name: AUTHORIZATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: AUTHORIZATION_SERVICE_URL