apiVersion: apps/v1
kind: Deployment
metadata:
  name: zos-connect-service
  namespace: services
  labels:
    app: zos-connect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zos-connect-service
  template:
    metadata:
      labels:
        app: zos-connect-service
    spec:
      containers:
        - name: zos-connect-service
          image: agilesolutions/zos-connect-service:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: ZOS_SERVICE_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: ZOS_SERVICE_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: LGTM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: LGTM_SERVICE_URL
            - name: RABBITMQ_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: RABBITMQ_SERVICE_URL