server:
  port: 8084

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus, refresh, bus-refresh, bus-env

spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8091/"
  # Spring Bus for RabbitMQ to refresh configuration across services
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  mvc:
    apiversion:
        use-header: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8092


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  #  enable-spring-security: true
  #  show-login-endpoint: true
  #  show-oauth2-endpoints: true
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

twelvedata:
  api:
    url: https://api.twelvedata.com/
    key: demo

service:
  retry:
    initial_delay: 1000
    max-delay: 5000
    multiplier: 2.0
    max-attempts: 3

logging:
  level:
    root: INFO

info:
  app:
    name: "Product Service"
    description: "Service responsible for managing product information and providing product-related APIs."
    version: "1.0.0"