apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-service
  namespace: services
  labels:
    app: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
        - name: authorization-service
          image: agilesolutions/authorization-service:1.0.0
          ports:
            - containerPort: 8092
          env:
            - name: AUHORIZATION_SERVICE_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: AUHORIZATION_SERVICE_APPLICATION_NAME
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
