-- =============================================================================
-- V1__create_accounts_table.sql
-- Creates the accounts table (H2 compatible)
--
-- COBOL equivalent:
--   FD  ACCTDAT
--       LABEL RECORDS ARE STANDARD
--       RECORD CONTAINS 500 CHARACTERS.
--   01  ACCOUNT-RECORD.
--     05 ACCT-ID              PIC X(11).
--     05 ACCT-ENTITY-CD       PIC X(25).
--     05 ACCT-TYPE-CD         PIC X(1).
--     05 ACCT-ACTIVE-STATUS   PIC X(1).
--     05 ACCT-CURR-BAL        PIC S9(10)V99 COMP-3.
--     05 ACCT-CREDIT-LIMIT    PIC S9(10)V99 COMP-3.
--     ... etc
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Drop table if exists (H2 safe syntax)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS accounts;

-- -----------------------------------------------------------------------------
-- accounts table
-- -----------------------------------------------------------------------------
CREATE TABLE accounts (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          VARCHAR(11)     NOT NULL,
    account_name        VARCHAR(25),
    account_type        VARCHAR(1)      NOT NULL,
    active_status       VARCHAR(1)      NOT NULL DEFAULT 'Y',
    curr_bal            DECIMAL(12,2)   DEFAULT 0.00,
    credit_limit        DECIMAL(12,2)   DEFAULT 0.00,
    cash_credit_limit   DECIMAL(12,2)   DEFAULT 0.00,
    open_date           DATE,
    expiry_date         DATE,
    reissue_date        DATE,
    curr_cycle_credit   DECIMAL(12,2)   DEFAULT 0.00,
    curr_cycle_debit    DECIMAL(12,2)   DEFAULT 0.00,
    addr_zip            VARCHAR(10),
    addr_state          VARCHAR(20),
    addr_country        VARCHAR(20),
    addr_line1          VARCHAR(50),
    addr_line2          VARCHAR(50),
    phone_number_1      VARCHAR(15),
    phone_number_2      VARCHAR(15),
    group_id            VARCHAR(10),
    student_ind         VARCHAR(1)      DEFAULT 'N',
    over_limit_ind      VARCHAR(1)      DEFAULT 'N',
    created_by          VARCHAR(50),
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(50),
    updated_at          TIMESTAMP,
    version             BIGINT          DEFAULT 0,

    -- Constraints
    CONSTRAINT uq_accounts_account_id
        UNIQUE (account_id),

    CONSTRAINT chk_accounts_active_status
        CHECK (active_status IN ('Y','N')),

    CONSTRAINT chk_accounts_account_type
        CHECK (account_type IN ('1','2')),

    CONSTRAINT chk_accounts_student_ind
        CHECK (student_ind IN ('Y','N')),

    CONSTRAINT chk_accounts_over_limit_ind
        CHECK (over_limit_ind IN ('Y','N')),

    CONSTRAINT chk_accounts_curr_bal
        CHECK (curr_bal >= -99999999.99),

    CONSTRAINT chk_accounts_credit_limit
        CHECK (credit_limit >= 0.00),

    CONSTRAINT chk_accounts_cash_credit_limit
        CHECK (cash_credit_limit >= 0.00),

    CONSTRAINT chk_accounts_account_id_numeric
        CHECK (REGEXP_LIKE(account_id, '[0-9]{11}'))
);

-- -----------------------------------------------------------------------------
-- Indexes
-- COBOL: VSAM KSDS key index on ACCT-ID
-- -----------------------------------------------------------------------------
CREATE UNIQUE INDEX idx_accounts_account_id
    ON accounts (account_id);

CREATE INDEX idx_accounts_account_type
    ON accounts (account_type);

CREATE INDEX idx_accounts_active_status
    ON accounts (active_status);

CREATE INDEX idx_accounts_type_status
    ON accounts (account_type, active_status);

CREATE INDEX idx_accounts_over_limit
    ON accounts (over_limit_ind);

CREATE INDEX idx_accounts_open_date
    ON accounts (open_date);

CREATE INDEX idx_accounts_expiry_date
    ON accounts (expiry_date);

CREATE INDEX idx_accounts_group_id
    ON accounts (group_id);